[package]
name = "my_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
pathsearch = "0.2.0"
thiserror = "1.0.38"                             # error handling
